"""HTML report generation with charts."""

import base64
import io
import os
from datetime import datetime

import matplotlib
import matplotlib.pyplot as plt

matplotlib.use("Agg")  # Non-interactive backend

from jinja2 import Template

from .models import AnalysisResult

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>トレーニングレポート {{ date }}</title>
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #333; background: #f9f9f9; }
    h1 { color: #2c3e50; border-bottom: 3px solid #e74c3c; padding-bottom: 10px; }
    h2 { color: #2c3e50; margin-top: 30px; }
    .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }
    .card { background: white; border-radius: 8px; padding: 15px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); text-align: center; }
    .card .value { font-size: 2em; font-weight: bold; color: #e74c3c; }
    .card .label { font-size: 0.85em; color: #666; margin-top: 5px; }
    .charts { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 20px 0; }
    .chart-box { background: white; border-radius: 8px; padding: 15px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .chart-box img { width: 100%; }
    .advice-box { background: white; border-radius: 8px; padding: 25px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); white-space: pre-wrap; line-height: 1.7; }
    .zone-bar { background: #ecf0f1; border-radius: 4px; height: 24px; margin: 5px 0; position: relative; overflow: hidden; }
    .zone-fill { height: 100%; border-radius: 4px; display: flex; align-items: center; padding-left: 8px; font-size: 0.8em; color: white; font-weight: bold; }
    .z1 { background: #27ae60; }
    .z2 { background: #2ecc71; }
    .z3 { background: #f39c12; }
    .z4 { background: #e74c3c; }
    .alert { background: #ffeeba; border: 1px solid #ffc107; border-radius: 6px; padding: 12px; margin: 10px 0; }
    .good { background: #d4edda; border: 1px solid #28a745; }
    table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    th { background: #2c3e50; color: white; padding: 10px; text-align: left; }
    td { padding: 8px 10px; border-bottom: 1px solid #ecf0f1; }
    tr:hover { background: #f8f9fa; }
    footer { text-align: center; color: #aaa; font-size: 0.8em; margin-top: 40px; }
  </style>
</head>
<body>
  <h1>🏃 トレーニングレポート</h1>
  <p>生成日: {{ date }} | 集計期間: 過去 {{ num_weeks }} 週間</p>

  <div class="summary-grid">
    <div class="card"><div class="value">{{ total_activities }}</div><div class="label">アクティビティ数</div></div>
    <div class="card"><div class="value">{{ avg_weekly_km }}</div><div class="label">平均週間距離 (km)</div></div>
    <div class="card"><div class="value">{{ avg_weekly_h }}</div><div class="label">平均週間時間 (h)</div></div>
  </div>

  <h2>強度分布（Uphill Athlete 4ゾーン）</h2>
  {% if has_hr_data %}
  <div class="{{ '80_20_class' }}">
    低強度(Z1+Z2): <strong>{{ low_pct }}%</strong> / 目標: 80%以上
  </div>
  <div class="zone-bar"><div class="zone-fill z1" style="width:{{ z1_pct }}%">Z1 {{ z1_pct }}%</div></div>
  <div class="zone-bar"><div class="zone-fill z2" style="width:{{ z2_pct }}%">Z2 {{ z2_pct }}%</div></div>
  <div class="zone-bar"><div class="zone-fill z3" style="width:{{ z3_pct }}%">Z3 {{ z3_pct }}%</div></div>
  <div class="zone-bar"><div class="zone-fill z4" style="width:{{ z4_pct }}%">Z4 {{ z4_pct }}%</div></div>
  {% else %}
  <p>心拍データがないためゾーン分布を計算できません。心拍計を着用してください。</p>
  {% endif %}

  <div class="charts">
    <div class="chart-box"><h3>ゾーン時間分布</h3><img src="data:image/png;base64,{{ zone_chart }}" /></div>
    <div class="chart-box"><h3>週次走行距離トレンド</h3><img src="data:image/png;base64,{{ volume_chart }}" /></div>
  </div>

  <h2>最近のアクティビティ</h2>
  <table>
    <tr><th>日付</th><th>名前</th><th>距離</th><th>時間</th><th>平均心拍</th></tr>
    {% for act in recent_activities %}
    <tr>
      <td>{{ act.start_date.strftime('%Y/%m/%d') }}</td>
      <td>{{ act.name }}</td>
      <td>{{ "%.1f"|format(act.distance_km) }} km</td>
      <td>{{ "%.0f"|format(act.moving_time_min) }} 分</td>
      <td>{{ "%.0f"|format(act.average_heartrate) if act.average_heartrate else "—" }} bpm</td>
    </tr>
    {% endfor %}
  </table>

  <h2>AIトレーニングアドバイス</h2>
  <div class="advice-box">{{ advice }}</div>

  <footer>Generated by Strava Training Advisor | Powered by Uphill Athlete methodology & Claude AI</footer>
</body>
</html>
"""


def _encode_figure(fig: plt.Figure) -> str:
    """Encode matplotlib figure as base64 PNG string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=120)
    buf.seek(0)
    encoded = base64.b64encode(buf.read()).decode("utf-8")
    plt.close(fig)
    return encoded


def _make_zone_chart(result: AnalysisResult) -> str:
    """Create a bar chart showing zone time distribution."""
    dist = result.overall_zone_distribution
    zones = ["Z1", "Z2", "Z3", "Z4"]
    hours = [
        dist.zone1_s / 3600,
        dist.zone2_s / 3600,
        dist.zone3_s / 3600,
        dist.zone4_s / 3600,
    ]
    colors = ["#27ae60", "#2ecc71", "#f39c12", "#e74c3c"]

    fig, ax = plt.subplots(figsize=(5, 3.5))
    bars = ax.bar(zones, hours, color=colors, edgecolor="white", linewidth=0.5)
    ax.set_ylabel("時間 (h)")
    ax.set_title("ゾーン別時間分布")
    for bar, h in zip(bars, hours):
        if h > 0:
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.02,
                f"{h:.1f}h",
                ha="center",
                va="bottom",
                fontsize=9,
            )
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    return _encode_figure(fig)


def _make_volume_chart(result: AnalysisResult) -> str:
    """Create a line chart showing weekly volume trend."""
    weeks = result.weeks
    labels = [ws.week_start.strftime("%m/%d") for ws in weeks]
    volumes = [ws.total_distance_km for ws in weeks]

    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.plot(labels, volumes, marker="o", color="#e74c3c", linewidth=2, markersize=5)
    ax.fill_between(range(len(volumes)), volumes, alpha=0.15, color="#e74c3c")
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=8)
    ax.set_ylabel("距離 (km)")
    ax.set_title("週次走行距離トレンド")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    return _encode_figure(fig)


def generate_report(result: AnalysisResult, advice: str, output_dir: str = "results") -> str:
    """Generate an HTML report and save it to output_dir."""
    os.makedirs(output_dir, exist_ok=True)

    dist = result.overall_zone_distribution
    has_hr_data = dist.total_s > 0
    low_pct = round(dist.low_intensity_pct, 1)
    z1_pct = round(dist.zone_pct(1), 1)
    z2_pct = round(dist.zone_pct(2), 1)
    z3_pct = round(dist.zone_pct(3), 1)
    z4_pct = round(dist.zone_pct(4), 1)

    zone_chart = _make_zone_chart(result)
    volume_chart = _make_volume_chart(result)

    template = Template(HTML_TEMPLATE)
    html = template.render(
        date=datetime.now().strftime("%Y年%m月%d日"),
        num_weeks=len(result.weeks),
        total_activities=result.total_activities,
        avg_weekly_km=f"{result.avg_weekly_km:.1f}",
        avg_weekly_h=f"{result.avg_weekly_h:.1f}",
        has_hr_data=has_hr_data,
        low_pct=low_pct,
        z1_pct=min(z1_pct, 100),
        z2_pct=min(z2_pct, 100),
        z3_pct=min(z3_pct, 100),
        z4_pct=min(z4_pct, 100),
        zone_chart=zone_chart,
        volume_chart=volume_chart,
        recent_activities=list(reversed(result.recent_activities)),
        advice=advice,
        **{"80_20_class": "alert good" if low_pct >= 80 else "alert"},
    )

    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    return filepath
